services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000