"""更新日時の追加

Revision ID: f7932601f47d
Revises: d601cfb841ee
Create Date: 2025-04-24 13:49:56.765533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7932601f47d'
down_revision = 'd601cfb841ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
